tashu_prediction/tashu/urls.py
from django.urls import path

from . import views

app_name = "tashu"
urlpatterns = [
	path('', views.index, name = 'index'),
	path('tashuStatus/', views.tashuStatus, name = 'tashuStatus'),
]

tashu_prediction/tashu_prediction/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
	path('tashu/', include('tashu.urls')),
    path('admin/', admin.site.urls),
]

tashu_prediction/tashu/models.py
from django.db import models
from selenium import webdriver
import pandas as pd
import time
import json
import datetime

# Create your models here.
class tashuCrawler:
    def currentStatusCrawler():
        url = "https://www.tashu.or.kr/userpage/station/mapStatus.jsp?flg=main"
        # execute chrome incogino mode
        chrome_options = webdriver.ChromeOptions()
        chrome_options.add_argument("--incognito")
        driver = webdriver.Chrome("linux_chrome_driver/chromedriver", chrome_options=chrome_options)

        ## connect to tashu web server
        driver.get(url)
        stationStatus = []
        #jsSourcecode = ("var strData;"+
        #	"strData = GDownloadUrl('/mapAction.do?process=statusMapView',"+
        #	" function(data, responseCode) {return data;}); ")

        jsSourcecode = ("var strData;"+
        "GDownloadUrl('/mapAction.do?process=statusMapView',"+
        "function(data, response){ dataDiv = document.createElement('div');"+
        "dataDiv.setAttribute('id', 'dataDiv');dataDiv.innerHTML = data;"+
        "document.body.appendChild(dataDiv);}); ")

        data = driver.execute_script(jsSourcecode)

        time.sleep(10)
        dataDIV = driver.find_element_by_id('dataDiv')
        dataTxt = dataDIV.text

        return dataTxt

    def parseData(data):
        jsonData = json.loads(data)
        stationData = jsonData['markers']
        returnDF = pd.DataFrame()

        currentDateTime = datetime.datetime.now()
        currentDateTime = datetime.datetime(currentDateTime.year, currentDateTime.month, currentDateTime.day, currentDateTime.hour)

        for station in stationData:
            stationNum = int(station['kiosk_no'])
            cntRackTotal = 0
            cntRentable = 0

            if stationNum > 0 and stationNum < 145:
                cntRackTotal = int(station['cntRackTotal'])
                cntRentable = int(station['cntRentable'])
                kiosk_no = int(station['kiosk_no'])
                returnDF = returnDF.append({'currentDateTime':currentDateTime, 'kiosk_no':stationNum, 'currentRentable':cntRentable, 'currentRackTotal':cntRackTotal},ignore_index=True)

        return returnDF

tashu_prediction/tashu/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
#from models import tashuCrawler
from .models import tashuCrawler
import json
from datetime import datetime
import os

# Create your views here.
def index(request):
	return render(request, 'tashu/index.html',)

def tashuStatus(request):
	input_stationNum = request.GET['input_stationNum']
	with open('/home/minjiwon/Documents/tashu_crawler/tashu_crawler/crawl_data/test.json') as crnt_Data:
		oneday_feature_data = json.load(crnt_Data)

	context ={}
	context = oneday_feature_data['hour_'+str(datetime.now().hour)]
	context['input_stationNum'] = input_stationNum
	#context = {'temperature': '2.0', 'input_stationNum': '1', 'humidity': '56', 'rainfall': 0, 'snowfall': 0, 'hour': 11, 'month': 1, 'windspeed': '1.2', 'weekday': 2, 'season': '4'}

	#execute R prediction code
	os.system("Rscript /home/minjiwon/tashuPrediction/test.R")
	
	return render(request, 'tashu/tashuStatus.html',context)

tashu_prediction/tashu/templates/tashu/index.html
{% load static %}
<html>
  <head>
    <title>타슈 실시간 예측</title>
    <link rel = "stylesheet" type = "text/css" href = "{% static 'tashu/main_css.css' %}"/>
  </head>
  <body>
    <div id = "main">
      <div id = "imgBox" width = "200px" height="200px">
        <img id = "tashu_logo" src = "{% static 'tashu/tashu_logo.jpg' %}" width = "200px" height="200px"></img>
      </div>
      <div id = "titleBox">
        <h1 id = "titleText">타슈 실시간 예측 시스템 </h1>
      </div>
    </div>
    <h1>정류소 번호를 입력하시오.(1~144)</h1>
    <form action = "{%  url 'tashu:tashuStatus' %}" method= "get">
    {% csrf_token %}
    <input type = "text" name = "input_stationNum" id = "input_stationNum"/>
    <input type = "submit" value = "입력" />
    </form>
  </body>
</html>

tashu_prediction/tashu/templates/tashu/tashuStatus.html
{% load static %}
<html>
  <head>
    <title>{{input_stationNum}} 번 정류소 예측</title>
    <link rel = "stylesheet" type = "text/css" href = "{% static 'tashu/tashuStatus/prediction_page_css.css' %}"/>
  </head>
  <body>
    <div id = "topBox">
      <h1>{{input_stationNum}} 번 정류소 예측 결과</h1>
    </div>
    <div id = "middleBox">
      <div id = "tashu_status">
        <div id = "tashu_map_status">
          <h3>실시간 타슈 현황</h3>
          <iframe src = "https://www.tashu.or.kr/userpage/station/mapStatus.jsp?" width = "740" height="400" scrolling="auto" border="0" marginwidth = "0"></iframe>
        </div>
        <div id = "tmp_id">
          <h3>준비중</h3>
          <img src = "{% static 'tashu/tashuStatus/img_ready.jpg' %}" width = "740" height= "400"></img>
        </div>
      </div>
      <div>
        <h3>실시간 요인 데이터</h3>
        <div class = "table_div_box">
          <table id = "crnt_feature_data">
            <tr>
              <th>월</th>
              <th>시간</th>
              <th>요일</th>
              <th>계절</th>
              <th>기온</th>
              <th>습도</th>
              <th>풍속</th>
              <th>강수량</th>
              <th>적설량</th>
            </tr>
            <tr>
              <td>{{month}}</td>
              <td>{{hour}}</td>
              <td>{{weekday}}</td>
              <td>{{season}}</td>
              <td>{{temperature}}</td>
              <td>{{humidity}}</td>
              <td>{{windspeed}}</td>
              <td>{{rainfall}}</td>
              <td>{{snowfall}}</td>
            </tr>
          </table>
        </div>
      </div>
      <div class = "table_div_box">
        <h3>실시간 예측 결과</h3>
        <div class = "table_div_box">
          <table id = "prediction_history">
            <tr>
              <th>일시</th>
              <th>예측 대여량</th>
              <th>예측 반납량</th>
              <th>실제 대여량</th>
              <th>실제 반납량</th>
            </tr>
            <tr>
            </tr>
        </table>
      </div>
      </div>
    </div>
    <div id = "footerBox"></div>
  </body>
</html>